[package]
name = "rocket-include-dir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = { version = "0.7.3", default-features = false }
rocket = { version = "0.5.0", default-features = false }
